### ISSUE TITLE
Build warnings concerning packages

### ISSUE THREAD

**Issue by Juul** [sudomesh/sudowrt-firmware#1]
WARNING: No feed for package 'md5sum' found, maybe it's already part of the standard packages?

WARNING: No feed for package 'libustream-cyassl' found, maybe it's already part of the standard packages?

**Comment by max-b** [comment]
As of this comment it looks like we have the following warnings:
`WARNING: No feed for package 'luci-mod-admin-core' found, maybe it's already part of the standard packages?`
`WARNING: No feed for package 'luci-proto-core' found, maybe it's already part of the standard packages?`
`WARNING: No feed for package 'luci-mod-admin-core' found, maybe it's already part of the standard packages?`
`WARNING: No feed for package 'ifplugd' found, maybe it's already part of the standard packages?`
I don't think there's any reason to worry about these. I'm certain we don't actually need/use ifplugd, and the luci packages should soon be replaced with luci2 web stuff. Also these warnings haven't broken any builds or caused any other errors, so I think we're fine :)
