### ISSUE TITLE
Connecting to Pico2 but not to internet

### ISSUE THREAD

**Issue by TinajaLabs** [sudomesh/sudowrt-firmware#10]
Connected directly to Ethernet of Comcast cable modem.  The connection to the wifi router is made, but connection to internet fails.

Settings when connected to peoplesopen.net:
IPv4: 10.0.7.106, 255.255.255.0
Default Gateway: 10.42.10.10
DHCP: 10.0.7.1
DNS: 10.42.10.10

Settings when connected to private SSID:
IPv4: 172.30.0.145, 255.255.255.0
Default Gateway: 172.30.0.1
DHCP: 172.30.0.1
DNS: 172.30.0.1

Please advise on further troubleshooting.
chris@tinajalabs.com

**Comment by Juul** [comment]
No longer relevant. So much has changed.
