### ISSUE TITLE
soundcloud.com 403 Unauthorized on PON (not on regular connection)

### ISSUE THREAD

**Issue by Juul** [sudomesh/sudowrt-firmware#100]
https://soundcloud.com/

reported by jerkey

**Comment by jhpoelen** [comment]
I was able to play https://soundcloud.com/kodak-black/roll-in-peace-feat through PON's exit node at Psychz Networks in LA. 

![screenshot from 2017-11-07 22-30-16](https://user-images.githubusercontent.com/1084872/32534660-691b47b2-c40b-11e7-87a7-b1b7cf22708e.png)

@jerkey please re-open if this is still an issue.
