### ISSUE TITLE
Trouble connecting to internet through node's public and private networks

### ISSUE THREAD

**Issue by wrought** [sudomesh/sudowrt-firmware#11]
Set up node, connected to http://my.node, changed wifi password, reconnected successfully, but unable to access internet. Internet is provided to the node by ethernet cable to generic linksys WRT router with default firmware (not openwrt or ddwrt), which in turn is connected to cable modem from comcast, basic service (xfinity?).

`
$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN qlen 1000
    link/ether 00:1e:37:ce:5f:de brd ff:ff:ff:ff:ff:ff
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc mq state UP qlen 1000
    link/ether 00:1f:3b:39:d2:5b brd ff:ff:ff:ff:ff:ff
    inet 172.30.0.117/24 brd 172.30.0.255 scope global wlan0
    inet6 fe80::21f:3bff:fe39:d25b/64 scope link 
       valid_lft forever preferred_lft forever
`

**Comment by max-b** [comment]
This is likely no longer relevant to our new set of configurations.
