### ISSUE TITLE
firmware build script is using HEAD of openwrt 15.05

### ISSUE THREAD

**Issue by jhpoelen** [sudomesh/sudowrt-firmware#112]
in [openwrt_config/version](../blob/master/openwrt_config/version) ```15.05:HEAD``` is specified. Since the 15.05 branch is active, this means that a commit by an openwrt developer can lead to unexpected variations in our firmware builds.

Suggest to set the openwrt version to 15.05:0c335d6ea00af9b32225f72d491e560c1a7cf4ab which points to the last official chaos calmer release v15.05.1 .

A hint toward this is that the builds scripts expects to build off of a openwrt commit with a tag and complains otherwise (see https://github.com/sudomesh/sudowrt-firmware/issues/110#issuecomment-342002008 ) .

**Comment by Juul** [comment]
Sounds good to me!

**Comment by jhpoelen** [comment]
done.
