### ISSUE TITLE
remove captive portal remains

### ISSUE THREAD

**Issue by jhpoelen** [sudomesh/sudowrt-firmware#117]
@juul suggests to remove fakecaptive portal remainders in home node firmware.

**Comment by bennlich** [comment]
Is this the "welcome to this wifi network" popup that shows up when you first connect to the peoplesopen network?

**Comment by jhpoelen** [comment]
@bennlich yep - although, I've never seen it.

**Comment by jnny** [comment]
can we close this?

**Comment by paidforby** [comment]
No longer an issue as far as I am aware. Changes made in makenode have been rolled into firmware since v0.3.0.
