### ISSUE TITLE
create operator manual

### ISSUE THREAD

**Issue by jhpoelen** [sudomesh/sudowrt-firmware#118]
Create operator manual to help folks like myself troubleshoot home, extender and exit nodes. 

Content would include: network diagram (how is a home node configured), troubleshooting recipes (how to check that a node is meshing?).

Please holler if such a manual already exists.

**Comment by paidforby** [comment]
I agree, an definitive operator's manual would be nice. I am interested on working on the needed documentation and test systems. I would also like to understand how to put something on the mesh once I have a node? Seems like a logical next step, hence my reason for opening [bug 9](https://github.com/sudomesh/bugs/issues/9).

**Comment by jhpoelen** [comment]
@paidforby here's a first pass https://github.com/sudomesh/sudowrt-firmware/blob/master/operator_manual.md . I can imagine that setting up a hello world service could be part of this.
