### ISSUE TITLE
sudowrt firmware broken - 15.05 branch of openwrt no longer seems to exist

### ISSUE THREAD

**Issue by jhpoelen** [sudomesh/sudowrt-firmware#123]
```git clone git://git.openwrt.org/15.05/openwrt.git```

worked up until about 2 days ago (~1 jan 2018, see attached screenshot).

![screenshot from 2018-01-03 20-23-49](https://user-images.githubusercontent.com/1084872/34550277-62763670-f0c4-11e7-8bab-be5bdc6d22f8.png)

**Comment by paidforby** [comment]
Thanks for reporting, just noticed this also. Who deleted the 15.05 branch, we were using that!

**Comment by paidforby** [comment]
attempting to fix with:
```
git clone "git://github.com/openwrt/chaos_calmer.git"
```

Now failing at:
```
oldpackages:src-git oldpackages git://git.openwrt.org/15.05/openwrt.git
```
in [openwrt_config/feeds](https://github.com/sudomesh/sudowrt-firmware/blob/master/openwrt_config/feeds) is also broken by this.

**Comment by paidforby** [comment]
All references to `git://git.openwrt.org/15.05/openwrt.git` have been replaced with `git://github.com/openwrt/chaos_calmer.git` still building off tagged commit `0c335d6ea00af9b32225f72d491e560c1a7cf4ab`. Need to test full build to see if there were any adverse side effects, particularly with the oldpackages switch, but for now it is passing.

**Comment by paidforby** [comment]
side note: looks like 15.05 was archived at `https://git.archive.openwrt.org/15.05/openwrt.git`

**Comment by paidforby** [comment]
Apologies for all the commits and reverts, decided to make simplest change, inserted "archive" between "git" and "openwrt" as seen in 6c16f45bb80a4daef27bfa2058d482ca364bfcb5

**Comment by jhpoelen** [comment]
thanks for making this happen. Does that mean that the head commit stays the same?

**Comment by jhpoelen** [comment]
btw - should we turn travis notifications on for all contributors? Now, I am not catching the build that you triggered..

**Comment by paidforby** [comment]
I'm not sure what is meant by them "archiving" it if that is what you are asking? It looks like the [openwrt/chaos_calmer](github.com/openwrt/chaos_calmer.git) repo is still being developed.

I don't mind getting notifications on failed builds, but I guess it should be an opt-in, right.

Also, we should move the 0.2.1 tag to 6c16f45bb80a4daef27bfa2058d482ca364bfcb5, since the old stable commit will now fail.

**Comment by jhpoelen** [comment]
I'd suggest to create a new tag. In my mind , the tag is for the docker build image.

**Comment by jhpoelen** [comment]
My question about the commit was whether the openwrt commit hash we use now has changed. I can also have a look at the version file in the build repo. Just being lazy.

**Comment by paidforby** [comment]
understood on the tag, whoever gets to it first can tag it accordingly 

we're still checking out the same commit, for your convenience https://github.com/sudomesh/sudowrt-firmware/blob/master/openwrt_config/version, as far as I can tell there is no difference between the old, active openwrt 15.05 repo and the archived repo (that is, it still recognizes the same commits and tags).
