### ISSUE TITLE
prepare script doesn't work on zipfile downloads

### ISSUE THREAD

**Issue by Deekoo** [sudomesh/sudowrt-firmware#13]
Minor bug - if you download the zip and then run prepare, it complains that it's not a git repository:

sudomesh@transfinity:~/sudowrt-firmware-master$ ./prepare 
Checking working directory
No URL in (/usr/bin/git describe --always)
About to exec (/usr/bin/git describe --always)
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

Getting the repo by git cloning the https URL works, though.

**Comment by Juul** [comment]
fixed
