### ISSUE TITLE
Consider running polipo

### ISSUE THREAD

**Issue by Juul** [sudomesh/sudowrt-firmware#22]
polipo is used by both the EFF firmware and Open Garden to speed up the browsing experience. It really does work. We should consider setting it up. Here is the config from the EFF firmware:

  https://github.com/EFForg/OpenWireless/blob/master/etc/config/polipo

**Comment by max-b** [comment]
What do we think about the node's ability to run this considering their software constrained speeds? Do you think that with the new hardware it won't really be a big deal?

**Comment by max-b** [comment]
Well just installed polipo on one of the nodes in my house and it really does speed up web browsing (can't just be placebo can it?)!

I'll keep an eye on resource usages, but for now it looks fine.

**Comment by max-b** [comment]
I added polipo to the packages list and a config to makenode
https://github.com/sudomesh/makenode/commit/77fb9b0171d335feb8bf9911cea32a48b1e11fae
https://github.com/sudomesh/sudowrt-firmware/commit/f5822c37a2b57b3558f8a9014456aa07497bc803

So far resource usages look ok on the node that has been running polipo:
http://192.241.217.196/cacti/graph_view.php?action=tree&tree_id=1&leaf_id=40&select_first=true

We can keep an eye on them.
