### ISSUE TITLE
Support Nanostation M2 and M5 as extender nodes

### ISSUE THREAD

**Issue by Juul** [sudomesh/sudowrt-firmware#29]
Since these devices have a built-in switch we need a somewhat different configuration and hook script.

**Comment by max-b** [comment]
Nanostation m2 is working as of: 5d902ee4a8a1995deb43a352d7533788af215aa0

m5 should be pretty similar. I have one so I can look into it a little further.

**Comment by max-b** [comment]
And we have the nanostation m5 working!

Right now the second ethernet port is just basically for debugging, but we can eventually think about some fancy VLAN/POE chaining ideas.
