### ISSUE TITLE
Complete new home-node web UI 

### ISSUE THREAD

**Issue by Juul** [sudomesh/sudowrt-firmware#34]
So we can finally ditch luci.

**Comment by max-b** [comment]
I've got a working, basic implementation of the web ui: https://github.com/sudomesh/sudowrt-web-ui/commit/773f2e18ea90633191c9ff53dffb254f92089469

which can be installed by this package:
https://builds.sudomesh.org/builds/chaos_calmer/ar71xx/packages/peopleswifi/sudowrt-web-ui_0.0.1-HEAD_ar71xx.ipk

**Comment by max-b** [comment]
Firmwares are now defaulting to build with `sudowrt-web-ui` and not luci. All of the features we had previously listed are available now: changing private ssid and password; amount of bandwidth to share; and admin password.

The web ui could use better feedback for things loading/saving.

**Comment by max-b** [comment]
I'm gonna close this ticket as is and we can pick individual pieces of polishing the home node web ui and ticket them separately.
