### ISSUE TITLE
Extender-node management via home-node UI

### ISSUE THREAD

**Issue by Juul** [sudomesh/sudowrt-firmware#35]
We'll need to implement a [https://github.com/sudomesh/ubus-https-forwarder](ubus https forwarder) and implement the features in client side js/html.

**Comment by eenblam** [comment]
@Juul can we close this? Seems less relevant if we're moving away from supporting extender nodes.

**Comment by paidforby** [comment]
@eenblam agreed, seems no longer relevant, and unlikely to be worked on any time soon. See https://github.com/sudomesh/sudowrt-firmware/issues/38#issuecomment-428401179 for more of the state of extender nodes
