### ISSUE TITLE
Automatically discover and select a VPuN (relay) server

### ISSUE THREAD

**Issue by Juul** [sudomesh/sudowrt-firmware#43]
We need to be able to run multiple VPuN servers and have the clients discover them and try connecting to them one by one until one succeeds.

**Comment by Juul** [comment]
Mitar pointed out that we don't want multiple exit servers though, since lots of stuff won't like it when the user switches IPs. If we get an AS number there are ways to deal with this.

**Comment by paidforby** [comment]
this is fixed by patch for https://github.com/sudomesh/bugs/issues/17 closing duplicate

**Comment by bennlich** [comment]
@paidforby Is a VPuN relay server the same thing as an exit node?

**Comment by paidforby** [comment]
Yes, as far as I know. VPuN is a "Virtual Public Network" so essentially another term for the "Mesh Area Network" or the "network" created by tunneldigger and routed over by babel.

**Comment by bennlich** [comment]
👍
