### ISSUE TITLE
Hardware watchdog support

### ISSUE THREAD

**Issue by Juul** [sudomesh/sudowrt-firmware#48]
ar71xx and newer supposedly have hardware watchdogs so we should use them

**Comment by max-b** [comment]
I think it's already running by default:
```
root@my:~# ubus call system watchdog
{
        "status": "running",
        "timeout": 30,
        "frequency": 5
}
```

**Comment by Juul** [comment]
Ok we should figure out how to disable that. I started implementing [this](https://github.com/sudomesh/watchpuppy) instead.

**Comment by eenblam** [comment]
Please see [watchpuppy](github.com/sudomesh/watchpuppy) for @juul's solution. Please see [monitor](https://github.com/sudomesh/monitor) for our current monitoring infrastructure.

**Comment by bennlich** [comment]
Hmmmm. I ran the command @max-b mentioned on my node, and got the same result, so I guess it's still running on our nodes.

@Juul why did you want to disable and replace with the puppy?
