### ISSUE TITLE
Manually specify frequency for Babel channel diversity

### ISSUE THREAD

**Issue by Juul** [sudomesh/sudowrt-firmware#49]
Currently Babel isn't able to figure out the freaquency of wifi radios (this will be fixed at some point) so we need to set the frequency in the babeld conf ourselves

**Comment by max-b** [comment]
Ok I've got this in 334613a 

This ends up being relevant to https://github.com/sudomesh/sudowrt-firmware/issues/51, so we should make sure we get it all incorporated.

**Comment by max-b** [comment]
Oh and also of course we're gonna need to eventually get the other hosts, including the mynets and the extender nodes to incorporate the same.

**Comment by Juul** [comment]
Yeah. I can add it to the extender nodes. This will also need to be incorporated into the web UI so that changing frequency on e.g. an extender node also changes the babel frequency setting

**Comment by max-b** [comment]
I added it to extender nodes: 0cb3525520dba710237b973f5214c6ef244c5436
