### ISSUE TITLE
Wifi config problem with ar71xx build

### ISSUE THREAD

**Issue by Juul** [sudomesh/sudowrt-firmware#5]
It seems that ar71xx devices will not function correctly if the macaddr option is not set in /etc/config/wireless under the wifi-device section.

If the macaddr line is removed, then the "wifi" command won't work to activate the network card and a new wifi-device section and a new wifi-iface section will be added to the config file on next boot (and it will have the disabled flag set).

Since we're over-writing /etc/config/wireless with no regard to mac address, this effectively disables wifi and possibly causes problem with mac-address detection in the node-configurator client.

```
config wifi-device  radio0
      option type     mac80211
      option channel  11
      option macaddr  0c:82:68:b3:67:54
      option hwmode   11ng
      option htmode   HT20
      list ht_capab   SHORT-GI-20
      list ht_capab   SHORT-GI-40
      list ht_capab   RX-STBC1
      list ht_capab   DSSS_CCK-40

config wifi-iface
      option device   radio0
      option network  lan
      option mode     ap
      option ssid     OpenWrt
      option encryption none
```

**Comment by max-b** [comment]
Seems fixed
