### ISSUE TITLE
Select default wifi frequencies for extender nodes

### ISSUE THREAD

**Issue by Juul** [sudomesh/sudowrt-firmware#52]
Should be non-overlapping with home node

**Comment by max-b** [comment]
This can now be done in openwrt_config/extender-node-vars.cfg as of 0cb3525520dba710237b973f5214c6ef244c5436

**Comment by Juul** [comment]
Nice! Channel 36 with 40 mhz width is not allowed in the U.S. so I switched to channel 149 which can do 40 mhz non-overlapping with channel 157 (also 40 mhz) which we use for home nodes. Neither of these channels require DFS.
