### ISSUE TITLE
99_wireless script sed lines fail

### ISSUE THREAD

**Issue by Juul** [sudomesh/sudowrt-firmware#58]
The script deletes itself (indicating success) but the sed lines at the bottom of the script don't work. I tried manually running:

```
export CHANNEL_5=149
sed -i "/{5_CHANNEL}/c\  option channel $CHANNEL_5" /etc/config/wireless
```

after boot, and it worked. So I don't know why it didn't work from the script. Maybe the problem was fixed after the last extender node firmware compile?

In any case we should fix the script so it checks exit status of sed and exits with fail status if sed fails, so we can at least go back and look at the script after it fails. Having a script fail and then delete itself is bad.

**Comment by max-b** [comment]
I believe this is working ok as of fe43dbba1166d7a4e2123f2345f3b3aca3d4fe45
