### ISSUE TITLE
ping to internet from non-internet-connected home node does not work

### ISSUE THREAD

**Issue by Juul** [sudomesh/sudowrt-firmware#64]
To replicate ssh into the /tmp/hearth node and ping 8.8.8.8

This is a firewall problem. This fixes the issue (but is bad):

```
iptables -P INPUT ACCEPT
```

**Comment by max-b** [comment]
Hey can you add my ssh key to that node so that I can take a look? I'll add yours to my test nodes.

**Comment by max-b** [comment]
I can't replicate this issue on any of my non-internet-connected home nodes....

**Comment by max-b** [comment]
Still no word and no other issues reported so I'm calling this closed.
