### ISSUE TITLE
ar71xx routers become unresponsive shortly after boot

### ISSUE THREAD

**Issue by Juul** [sudomesh/sudowrt-firmware#8]
A DHCP lease is requested by the node, given and accepted, but at no point can the node be pinged or otherwise contacted. Status LED shows boot completed. This happens both an Nanostation M5 and TP-Link TL-WR703N.

We need to  hook up a serial console to check what's going wrong.

**Comment by Juul** [comment]
Fixed. Not sure who fixed it or how. Probably MaxB

**Comment by max-b** [comment]
lol yeah right, but thanks for the credit anyhow ;)
