### ISSUE TITLE
Colocation for tunnel server

### ISSUE THREAD

**Issue by max-b** [sudomesh/sudowrt-firmware#85]
We're definitely seeing traffic growth on our tunnel/exit server:

http://monitor.sudomesh.org/cacti/graph.php?action=view&local_graph_id=217&rra_id=all

![image](https://cloud.githubusercontent.com/assets/2491841/11604418/1b215abe-9aa1-11e5-8dab-22c31715e2e6.png)

Our digital ocean droplet will allow us 2TB per month, though we can scale that up by paying more:
https://www.digitalocean.com/pricing/

Ideally, though we'd finally find a reasonably priced colocation facility. Especially for before we do our first big public release.

**Comment by max-b** [comment]
We've since received sponsorship from digital ocean and it seems as though we're ok on the DMCA front. I'm pushing this back considering that we'll probably just want to put an exit server next to whatever ip transit link we eventually get.

**Comment by paidforby** [comment]
we have a new exit server at HE, and do not use digital ocean for any of our exit nodes, issue no longer relevant

**Comment by bennlich** [comment]
Seems like the Richmond tower would be a great place for this.
