### ISSUE TITLE
Upgrade node map version

### ISSUE THREAD

**Issue by max-b** [sudomesh/sudowrt-firmware#89]
We had talked about upgrading to nodeshot version 3(?) a while ago, but I dropped the ball on that. We should also look to see if we can find the source code for this map: https://map.hamburg.freifunk.net

**Comment by max-b** [comment]
Looks like the hamburg map is using this:
https://github.com/plumpudding/meshviewer

**Comment by paidforby** [comment]
suggested repo is no longer maintained, most work regarding monitoring and mapping is going on in https://github.com/sudomesh/monitor. Gonna close this since it doesn't seem directly related to the firmware. New issues regarding mapping should be opened in the aforementioned monitor repo.
