### ISSUE TITLE
Unable to establish PPPTP VPN connection on peoplesopen.net

### ISSUE THREAD

**Issue by thebalaa** [sudomesh/sudowrt-firmware#91]
Device: iPhone 6s, MacBook
OS: iOS 9.2.1, OS X El Capitan

Using built in VPN Client to connect to PPPTP VPN Server does not work, see attached screenshot. 
Works as expected on private network. I suspect it could be related to running PPPTP over tunnel digger

![image](https://cloud.githubusercontent.com/assets/109041/12510681/8fa89be6-c0c0-11e5-9833-63e079979bf5.png)

**Comment by max-b** [comment]
This is because pptp doesn't work natively behind a masquerading firewall (NAT). All traffic passes out of our exit server to the internet, where it's NATed, so pptp won't work naively. 

It looks like there's some way to enable "pptp passthrough" in the firewall rules, so I can look into that now.

**Comment by max-b** [comment]
@thebalaa - I added some iptables conntrack modules which I think should fix the issue. I was just successfully able to connect to a VPN over pptp over here. Can you try it on your end?

**Comment by thebalaa** [comment]
It works! Thanks, Max.

**Comment by max-b** [comment]
awesome. I added this as an issue to the provisioning scripts:
https://github.com/sudomesh/mesh-playbooks/issues/1
