### ISSUE TITLE
Consider removing polipo?

### ISSUE THREAD

**Issue by Juul** [sudomesh/sudowrt-firmware#95]
Do we want to consider removing polipo?

**Comment by jhpoelen** [comment]
@Juul could you elaborate?

**Comment by jnny** [comment]
polipo developed by @jech and no longer maintained. 

found active traces [here](https://github.com/sudomesh/sudowrt-firmware/blob/f0441f1c8dfc577eb29a8c80e1e774084b81f66f/files/opt/mesh/templates/etc/config/polipo) and [here](https://github.com/sudomesh/sudowrt-firmware/blob/3d10b2ef38c699601b99c3a1527fee71111fa1f8/files/opt/mesh/autoconf)
